### ISSUE TITLE
It doesn't seem this is bi-directional communication.  Only from iframe to parent window (or one window to another)

### ISSUE THREAD

**Issue by scottleedavis** [pshihn/windtalk#2]
Would be much more useful if it was bidirectional.

My current project is going to have to do this manually like:
https://gist.github.com/pbojinov/8965299

**Comment by pshihn** [comment]
oh but it is. See 'communicate with another window' example in https://github.com/pshihn/windtalk/wiki/Examples where each window sends a message to the other. 

Each window can call `windtalk.expose(object)` and call `windtalk.link(otherWindow)`

**Comment by scottleedavis** [comment]
Tried it with child iframe to parent... Didn't work. Add example if so
please?

**Comment by pshihn** [comment]
Here's a simple example: https://pshihn.github.io/windtalk/examples/window-bidirection.html
Code for the main window: https://github.com/pshihn/windtalk/blob/master/examples/window-bidirection.html
Code for the iframe: https://github.com/pshihn/windtalk/blob/master/examples/iframe-bidirection.html

The idea is quite simple. Whatever function or object you want the other window to use, call expose
```
windtalk.expose(function);
```

And to connect to the other window's exposed method or object, call link
```
const remoteFunction = windtalk.link(otherWindow)
remoteFunction();
```
